commands:
  # hour
  - commmand:
    input:  Que horas são?
    entity: time
    action: getTime
  - commmand:
    input:  Me digas horas.
    entity: time
    action: getTime
  - commmand:
    input:  Eu quero saber as horas.
    entity: time
    action: getTime
  # Date
  - commmand:
    input:  Qual é a data de hoje?
    entity: time
    action: getDate
  - commmand:
    input:  Data de hoje.
    entity: time
    action: getDate
  # Weather
  - commmand:
    input:  Previsão do tempo
    entity: weather
    action: getWeather
  - commmand:
    input:  Como está o clima?
    entity: weather
    action: getWeather
  # Open
  - commmand:
    input:  Abrir bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  Abrar o bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  Abrir chrome
    entity: open
    action: chrome
  - commmand:
    input:  Abra o google
    entity: open
    action: chrome
# greetings
  - commmand:
    input:  Bom dia 
    entity: hello
    action: getHello
  - commmand:
    input:  Boa tarde
    entity: hello
    action: getHello
# farewells   
  - commmand:
    input:  Adeus
    entity: farewells
    action: getFarewells
  - commmand:
    input:  Tchau 
    entity: farewells
    action: getFarewells
  - commmand:
    input:  Até logo
    entity: farewells
    action: getFarewells
