commands:

  # Hora
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me diga as horas.
    entity: time
    action: getTime

  # Data
  - command:
    input: Qual a data de hoje?
    entity: time
    action: getDate
  - command:
    input: Data de hoje.
    entity: time
    action: getDate    

  #Tempo  
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  - command:
    input: Como esta o clima?
    entity: weather
    action: getWeather    

  #Abrir  
  - command:
    input: Abrir google
    entity: open
    action: 
  - command:
    input: Abra youtube
    entity: open
    action:     